name: hello world workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: say hello world
        run: echo "hello world"
        shell: bash
  goodBye:
    runs-on: ubuntu-latest
    steps:
      - name: say goodbye world
        run: echo "goodbye world"
        shell: bash