name: Type1 Create a comment on new Issue using Actions
on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Dump GitHub Context
        run: echo "${{ toJSON(github.event) }}" | jq
        shell: bash

      - name: Create comment with action
        uses: peter-evans/create-or-update-comment@v3.0.1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for your feedback
            - We will soon reach out to you.! :sparkles:
            - Regards [Joseph Nannepaga]

          reactions: '+1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

